---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
spec:
  # Announce LoadBalancer IPs
  loadBalancerIPs: true
  # Interfaces to use for L2 announcements
  interfaces:
    - enp3s0
  # Use all nodes (single-node cluster)
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
