---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: observability
spec:
  interval: 1h
  chart:
    spec:
      chart: mimir-distributed
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deploymentMode: monolithic
    mimir:
      structuredConfig:
        common:
          storage:
            backend: filesystem
        limits:
          compactor_blocks_retention_period: 168h
    minio:
      enabled: false
    monolithic:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    ingester:
      replicas: 0
    distributor:
      replicas: 0
    querier:
      replicas: 0
    query_frontend:
      replicas: 0
    query_scheduler:
      replicas: 0
    ruler:
      replicas: 0
    compactor:
      replicas: 0
    store_gateway:
      replicas: 0
    rollout_operator:
      enabled: false
    nginx:
      enabled: false
    gateway:
      enabledNonNative: false
