---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "32.0.5"

    nextcloud:
      host: nextcloud.local
      username: admin
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: admin-username
        passwordKey: admin-password

    persistence:
      enabled: true
      storageClass: longhorn
      size: 500Gi

    # Use external MariaDB (official image, not Bitnami)
    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: mysql
      host: mariadb.nextcloud.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: db-username
        passwordKey: db-password

    # Disable bundled databases
    mariadb:
      enabled: false

    postgresql:
      enabled: false

    redis:
      enabled: false
